#!/usr/bin/env python3
"""Refresh the manuscript's inlined numbers from the analysis output.

submission.tex carries its fact macros inline so that it compiles on a bare
Overleaf project with no generated/ directory to upload. That convenience is
also a hazard: the inlined block can drift from what the analysis scripts
produce. This rebuilds it from paper/generated/*.tex, and copies the tables the
manuscript inputs into a generated/ folder beside it so the local build and the
flattened bundle resolve the same files.
"""
import os, re, shutil

HERE = os.path.dirname(os.path.abspath(__file__))
GEN = os.path.join(os.path.dirname(HERE), "generated")
OUT = os.path.join(HERE, "generated")
os.makedirs(OUT, exist_ok=True)

FACTS = ["facts.tex", "law_facts.tex", "rate_facts.tex"]
TABLES = ["table_rate.tex"]

macros = []
for f in FACTS:
    p = os.path.join(GEN, f)
    if not os.path.exists(p):
        raise SystemExit(f"missing {p}; run the analysis scripts first")
    for line in open(p):
        if line.startswith("\\newcommand"):
            macros.append(line.rstrip("\n"))

for t in TABLES:
    shutil.copy2(os.path.join(GEN, t), os.path.join(OUT, t))

p = os.path.join(HERE, "submission.tex")
s = open(p).read()
start = "%% Numbers quoted in the text, generated by the analysis pipeline."
end = "%% ---------------------------------------------------------------- front"
i, j = s.index(start), s.index(end)
block = start + "\n%% Rebuilt by sync_generated.py; do not edit by hand.\n" + \
        "\n".join(sorted(set(macros))) + "\n\n"
open(p, "w").write(s[:i] + block + s[j:])
print(f"inlined {len(set(macros))} macros, copied {len(TABLES)} table(s)")
