#!/usr/bin/env python3
"""Refresh the manuscript's inlined numbers from the analysis output.

submission.tex carries its fact macros inline so that it compiles on a bare
Overleaf project with no generated/ directory to upload. That convenience is
also a hazard: the inlined block can drift from what the analysis scripts
produce. This rebuilds it from paper/generated/*.tex, and copies the tables the
manuscript inputs into a generated/ folder beside it so the local build and the
flattened bundle resolve the same files.

It also rewrites sn-article-body.tex, the extract for pasting into the
publisher's own class, from submission.tex. That file was maintained by hand
and had already fallen a few edits behind, which is the worst kind of stale:
it looks like the manuscript and is not. Generating it removes the possibility.
"""
import os, re, shutil

HERE = os.path.dirname(os.path.abspath(__file__))
GEN = os.path.join(os.path.dirname(HERE), "generated")
OUT = os.path.join(HERE, "generated")
os.makedirs(OUT, exist_ok=True)

FACTS = ["facts.tex", "law_facts.tex", "rate_facts.tex"]
TABLES = ["table_rate.tex"]

macros = []
for f in FACTS:
    p = os.path.join(GEN, f)
    if not os.path.exists(p):
        raise SystemExit(f"missing {p}; run the analysis scripts first")
    for line in open(p):
        if line.startswith("\\newcommand"):
            macros.append(line.rstrip("\n"))

for t in TABLES:
    shutil.copy2(os.path.join(GEN, t), os.path.join(OUT, t))

p = os.path.join(HERE, "submission.tex")
s = open(p).read()
start = "%% Numbers quoted in the text, generated by the analysis pipeline."
end = "%% ---------------------------------------------------------------- front"
i, j = s.index(start), s.index(end)
block = start + "\n%% Rebuilt by sync_generated.py; do not edit by hand.\n" + \
        "\n".join(sorted(set(macros))) + "\n\n"
s = s[:i] + block + s[j:]
open(p, "w").write(s)

# ---- the extract for the publisher's own class ------------------------
HEADER = r"""% =====================================================================
% Body only, for dropping into the official Springer Nature template.
%
% On Overleaf: New Project -> Templates -> search "Springer Nature".
% Open it, then in its main .tex file:
%
%   1. keep the template's own \documentclass and the packages it loads,
%   2. paste the macro block below into that preamble,
%   3. delete everything from the template's \title down to, but not
%      including, its \end{document}, and paste the second block in its
%      place. That block carries its own \title, \author, \affil,
%      \begin{document} and \maketitle, so the template must not keep a
%      second copy of any of them,
%   4. upload the three PNGs and refs.bib to the project root,
%   5. set \bibliographystyle{sn-mathphys-num}, which that template ships.
%
% The sectioning, float style and Declarations block already match the
% template, so nothing else needs rewiring.
%
% Generated from submission.tex by sync_generated.py; do not edit by hand.
% =====================================================================

% ---------- paste into the preamble ----------
"""

body = s[s.index(end):s.index("\\end{document}")].rstrip() + "\n"
extract = (HEADER + block.rstrip() + "\n\n\n"
           + "% ---------- paste in place of the template's \\title ... "
             "\\end{document} ----------\n" + body)
open(os.path.join(HERE, "sn-article-body.tex"), "w").write(extract)

print(f"inlined {len(set(macros))} macros, copied {len(TABLES)} table(s), "
      f"regenerated sn-article-body.tex ({len(body.splitlines())} lines)")
