#!/usr/bin/env python3
"""Does the ceiling of the scaling law survive a change of link rate?

The law was fitted by sweeping path RTT at a fixed 10 Mbit/s bottleneck, so it
establishes that r = target/RTT governs the benefit along the RTT dimension and
says nothing about the other one. The serialisation campaign happens to supply
the missing axis: static and adapted pairs at 2, 5, 10, 20 and 50 Mbit/s, three
seeds each, all at a 5 ms path with the 5 ms default target, so r = 1 in every
cell and any variation in benefit is variation in the ceiling itself.

This script reports that variation and writes the table and fact macros the
papers cite, so the claim cannot drift from the measurements.
"""
import argparse, glob, json, math, os, statistics as st
from collections import defaultdict

import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from findings import welch

MTU_BITS = 1514 * 8


def load(resdir):
    out = []
    for f in sorted(glob.glob(os.path.join(resdir, "**", "summary.json"),
                              recursive=True)):
        try:
            out.append(json.load(open(f)))
        except Exception:
            pass
    return out


def ci95(xs):
    xs = [x for x in xs if x is not None]
    if len(xs) < 2:
        return (xs[0] if xs else None), 0.0, len(xs)
    t = {2: 12.706, 3: 4.303, 4: 3.182, 5: 2.776}.get(len(xs), 1.96)
    return st.fmean(xs), t * st.stdev(xs) / math.sqrt(len(xs)), len(xs)


def cells(runs, metric="bulk_rtt_mean_ms"):
    by = defaultdict(list)
    for r in runs:
        rate = r.get("rate_mbit")
        if rate is None or r.get(metric) is None:
            continue
        by[(float(rate), bool(r.get("adaptive")))].append(r[metric])
    out = []
    for rate in sorted({k[0] for k in by}):
        a, b = by.get((rate, False), []), by.get((rate, True), [])
        if len(a) < 2 or len(b) < 2:
            continue
        ma, ha, na = ci95(a)
        mb, hb, nb = ci95(b)
        _, _, p = welch(a, b)
        ser_ms = MTU_BITS / (rate * 1e6) * 1e3        # one MTU on the wire
        out.append(dict(rate=rate, static=ma, static_ci=ha, adapted=mb,
                        adapted_ci=hb, n=min(na, nb),
                        benefit=(ma - mb) / ma * 100.0, p=p,
                        ser_ms=ser_ms, s=5.0 / ser_ms))
    return out


def minimum_detectable(cs):
    """Smallest benefit this design could have resolved, as a percentage.

    Welch at n=3 per arm needs a separation of about t(0.975, 4) = 2.776
    pooled standard errors. Reporting it turns 'not significant' into a
    bound, which is the honest reading of a null at three repetitions.
    """
    worst = 0.0
    for c in cs:
        sa = c["static_ci"] / 4.303 * math.sqrt(3)     # back out sd
        sb = c["adapted_ci"] / 4.303 * math.sqrt(3)
        se = math.sqrt(sa ** 2 / 3 + sb ** 2 / 3)
        mde = 2.776 * se / c["static"] * 100.0
        worst = max(worst, mde)
    return worst


def pfmt(p):
    """A p-value of 0.0000 is a rounding artefact, not a measurement."""
    return "$<$0.0001" if p < 0.0001 else f"{p:.4f}"


def emit(cs, texdir, real):
    if not texdir or not real:
        return
    rows = "\n".join(
        f"{c['rate']:.0f} & {c['s']:.1f} & "
        f"{c['static']:.1f}\\,$\\pm$\\,{c['static_ci']:.1f} & "
        f"{c['adapted']:.1f}\\,$\\pm$\\,{c['adapted_ci']:.1f} & "
        f"{c['benefit']:+.1f} & {pfmt(c['p'])} \\\\"
        for c in cs)
    tab = ("% GENERATED by src/analyse_rate.py -- do not edit by hand.\n"
           "\\begin{tabular}{rrrrrr}\n\\toprule\n"
           "Link rate & $s$ & Static & Adapted & Benefit & $p$ \\\\\n"
           "(Mbit/s) & & (ms) & (ms) & (\\%) & \\\\\n\\midrule\n"
           + rows + "\n\\botrule\n\\end{tabular}\n")
    open(os.path.join(texdir, "table_rate.tex"), "w").write(tab)

    bens = [c["benefit"] for c in cs]
    m = {
        "RateCells": f"{len(cs)}",
        "RateMin": f"{min(c['rate'] for c in cs):.0f}",
        "RateMax": f"{max(c['rate'] for c in cs):.0f}",
        "RateBenefitMin": f"{min(bens):.1f}",
        "RateBenefitMax": f"{max(bens):.1f}",
        "RateSpread": f"{max(bens) - min(bens):.1f}",
        "RateRatio": f"{max(bens) / max(min(bens), 1e-9):.1f}",
        "RatePeakS": f"{max(cs, key=lambda c: c['benefit'])['s']:.1f}",
        "RateMDE": f"{minimum_detectable(cs):.1f}",
    }
    out = "% GENERATED by src/analyse_rate.py -- do not edit by hand.\n" + \
          "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in m.items())
    open(os.path.join(texdir, "rate_facts.tex"), "w").write(out)
    print(f"  wrote table_rate.tex and rate_facts.tex to {texdir}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results_serial")
    ap.add_argument("--texdir", default="")
    a = ap.parse_args()
    runs = load(a.results)
    cs = cells(runs)
    if not cs:
        raise SystemExit("no rate cells found in " + a.results)

    print("Benefit of adaptation at fixed r = 1, against link rate.")
    print("All cells use a 5 ms path and the 5 ms default target, so the")
    print("ratio is held at 1 and only the link rate changes.\n")
    print(f"{'rate':>6} {'s':>6} {'static':>16} {'adapted':>16} "
          f"{'benefit':>9} {'p':>8}")
    for c in cs:
        print(f"{c['rate']:6.0f} {c['s']:6.1f} "
              f"{c['static']:9.2f}+-{c['static_ci']:<5.2f} "
              f"{c['adapted']:9.2f}+-{c['adapted_ci']:<5.2f} "
              f"{c['benefit']:+8.1f}% {c['p']:8.4f}")
    bens = [c["benefit"] for c in cs]
    print(f"\n  spread {max(bens) - min(bens):.1f} percentage points, "
          f"a factor of {max(bens)/max(min(bens),1e-9):.1f}")
    print(f"  smallest benefit this design resolves: "
          f"{minimum_detectable(cs):.1f}%")
    print("\n  The ratio governs the RTT dimension. It does not fix the")
    print("  ceiling: at constant r the benefit still varies with link rate.")

    emit(cs, a.texdir, a.results == "results_serial")


if __name__ == "__main__":
    main()
